# Frontend Service Configuration
frontend:
  name: frontend
  replicaCount: 3
  image: 904119424941.dkr.ecr.ap-south-1.amazonaws.com/todo-frontend:v4
  port: 80
  targetPort: 80
  service:
    type: ClusterIP
    port: 80

# Backend Service Configuration
backend:
  name: backend
  replicaCount: 2
  image: 904119424941.dkr.ecr.ap-south-1.amazonaws.com/todo-backend:v4
  port: 5000
  targetPort: 5000
  service:
    type: ClusterIP
    port: 5000
  env:
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: rootpassword
    DB_NAME: booklibrary

# MySQL Configuration
mysql:
  enabled: true
  name: mysql
  image: mysql:8.0
  port: 3306
  service:
    type: ClusterIP
    port: 3306
  env:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: booklibrary
  persistence:
    enabled: true
    storageClass: gp2
    size: 10Gi

# Ingress Configuration
ingress:
  enabled: true
  hostname: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-8bab81e476bf6462,subnet-0d33d1209ef15cc44
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"

